version: "3"

services:
  bitcoind:
      restart: unless-stopped
      container_name: btcpayserver_bitcoind
      image: btcpayserver/bitcoin:0.19.0.1
      environment:
        BITCOIN_NETWORK: mainnet
        BITCOIN_WALLETDIR: "/walletdata"
        BITCOIN_EXTRA_ARGS: |
          rpcport=43782
          rpcbind=0.0.0.0:43782
          port=39388
          whitelist=0.0.0.0/0
      expose:
        - "43782"
        - "39388"
      volumes:
        - "./bitcoin_wallet_datadir:/walletdata"
        - "./bitcoin_datadir:/data"
      networks:
        - btcpay
  nbxplorer:
      environment:
        NBXPLORER_CHAINS: "btc"
        NBXPLORER_BTCRPCURL: http://bitcoind:43782/
        NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      volumes:
        - "./bitcoin_datadir:/root/.bitcoin"
  btcpayserver:
      environment:
        BTCPAY_CHAINS: "btc"
        BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/

