version: "3"

services:

  btcpayserver:
    restart: unless-stopped
    image: ${BTCPAY_IMAGE:-btcpayserver/btcpayserver:1.0.6.4$<BTCPAY_BUILD_CONFIGURATION>?}
    expose:
      - "49392"
    environment:
      # BTCPay settings
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: mainnet
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/btcpayserver/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: "true"
    links:
      - postgres
    networks:
      - nginx_net
      - btcpay
    volumes:
      - "./btcpay_datadir:/datadir"
      - "./nbxplorer_datadir:/root/.nbxplorer"

networks:
  btcpay:
  nginx_net:
    external: true

required:
  - "postgres"
  - "nbxplorer"
  - "btcpayserver"

recommended:
  - "opt-add-tor"
