version: "3"

services:
  postgres:
    restart: unless-stopped
    image:  postgres:9.6.5
    volumes:
      - "postgres_datadir:/var/lib/postgresql/data"
    networks:
      - btcpay

volumes:
    postgres_datadir:
